["Cocteau Twins"]
check = 2020-06-21

["Cocteau Twins".album."Blue Bell Knoll"]
date = 1988-09-19

["Cocteau Twins".album."Blue Bell Knoll".song]
"A Kissed Out Red Floatboat" = ""
"Athol-Brose" = "bad"
"Blue Bell Knoll" = ""
"Carolyn's Fingers" = ""
"Cico Buff" = "bad"
"Ella Megalast Burls Forever" = "bad"
"For Phoebe Still a Baby" = "bad"
"Spooning Good Singing Gum" = ""
"Suckling the Mender" = ""
"The Itchy Glowbo Blow" = "good"
