
["Cake"]

  ["Cake"."Fashion Nugget"]
    "@date" = "1996"
    "Daria" = "good"
    "Frank Sinatra" = "good"
    "Friend Is a Four Letter Word" = ""
    "I Will Survive" = ""
    "Italian Leather Sofa" = ""
    "It’s Coming Down" = ""
    "Nugget" = ""
    "Open Book" = ""
    "Perhaps, Perhaps, Perhaps" = "short"
    "Race Car Ya-Yas" = "short"
    "Sad Songs and Waltzes" = ""
    "She’ll Come Back to Me" = "short"
    "Stickshifts and Safetybelts" = "short"
    "The Distance" = ""

["Can"]

  ["Can"."Ege Bamyasi"]
    "@date" = "1972-11"
    "I’m So Green" = ""
    "One More Night" = ""
    "Pinch" = ""
    "Sing Swan Song" = ""
    "Soup" = ""
    "Spoon" = ""
    "Vitamin C" = "good"

["Cassie"]

  ["Cassie"."Cassie"]
    "@date" = "2006-08-08"
    "@yt" = "zVJ5gsLeCSM"
    "About Time" = ""
    "Call U Out" = ""
    "Ditto" = ""
    "Hope You’re Behaving (interlude)" = "short"
    "Just One Nite" = ""
    "Kiss Me" = ""
    "Long Way 2 Go" = ""
    "Me&U" = ""
    "Miss Your Touch" = "short"
    "Not With You" = ""
    "What Do U Want" = ""

["Chet Faker"]

  ["Chet Faker"."Built on Glass"]
    "/" = "short"
    "1998" = ""
    "@date" = "2014-04-11"
    "@yt" = "hi4pzKvuEQM"
    "Blush" = ""
    "Cigarettes & Loneliness" = ""
    "Dead Body" = ""
    "Gold" = ""
    "Lesson in Patience" = ""
    "Melt" = ""
    "No Advice (airport version)" = "short"
    "Release Your Problems" = ""
    "Talk is Cheap" = ""
    "To Me" = ""

["Chicago"]

  ["Chicago"."Chicago 17"]
    "@date" = "1984-05-14"
    "@yt" = "wM-XhQeFzW4"
    "Along Comes a Woman" = ""
    "Hard Habit to Break" = ""
    "Once in a Lifetime" = ""
    "Only You" = ""
    "Please Hold On" = ""
    "Prima Donna" = ""
    "Remember the Feeling" = ""
    "Stay the Night" = ""
    "We Can Stop the Hurtin’" = ""
    "You’re the Inspiration" = ""

  ["Chicago"."Chicago II"]
    "25 or 6 to 4" = "good"
    "@date" = "1969"
    "A.M. Mourning" = "short"
    "Anxiety’s Moment" = "short"
    "Colour My World" = ""
    "Fancy Colours" = ""
    "In the Country" = ""
    "It Better End Soon (1st Movement)" = "short"
    "It Better End Soon (2nd Movement)" = ""
    "It Better End Soon (3rd Movement)" = ""
    "It Better End Soon (4th Movement)" = "short"
    "Make Me Smile" = ""
    "Memories of Love" = ""
    "Movin’ In" = ""
    "Now More Than Ever" = "short"
    "P.M. Mourning" = "short"
    "Poem for the People" = ""
    "Prelude" = "short"
    "So Much to Say, So Much to Give" = "short"
    "The Road" = ""
    "To Be Free" = "short"
    "Wake Up Sunshine" = "short"
    "West Virginia Fantasies" = "short"
    "Where Do We Go From Here" = "short"

  ["Chicago"."Chicago V"]
    "@date" = "1972"
    "A Hit by Varèse" = ""
    "All Is Well" = ""
    "Alma Mater" = ""
    "Dialogue, Part I" = "short"
    "Dialogue, Part II" = ""
    "Goodbye" = ""
    "Now That You’ve Gone" = ""
    "Saturday in the Park" = "good"
    "State of the Union" = ""
    "While the City Sleeps" = ""

  ["Chicago"."Chicago X"]
    "@date" = "1976"
    "Another Rainy Day in New York City" = ""
    "Gently I’ll Wake You" = ""
    "Hope for Love" = ""
    "If You Leave Me Now" = "good"
    "Mama Mama" = ""
    "Once or Twice" = ""
    "Scrapbook" = ""
    "Skin Tight" = ""
    "Together Again" = ""
    "You Are on My Mind" = ""
    "You Get It Up" = ""

["Chicane"]

  ["Chicane"."Behind the Sun"]
    "@date" = "2000-03-27"
    "Andromeda" = "bad"
    "Autumn Tactics" = "bad"
    "Don't Give Up" = "bad"
    "Halcyon" = "bad"
    "Low Sun" = "good"
    "No Ordinary Morning" = "bad"
    "Overlap" = "bad"
    "Overture" = "good"
    "Saltwater (The Thrillseekers remix)" = "good"
    "Saltwater (original mix)" = "good"

  ["Chicane"."Far From the Maddening Crowds"]
    "@date" = "1997"
    "Already There" = "short"
    "Early" = ""
    "From Blue to Green" = ""
    "Leaving Town" = ""
    "Lost You Somewhere" = ""
    "Offshore (original mix)" = ""
    "Offshore ’97" = "good"
    "Red Skies" = ""
    "Sunstroke (Disco Citizens remix)" = ""
    "Sunstroke (original mix)" = ""
    "The Drive Home" = ""

  ["Chicane"."Somersault"]
    "@date" = "2007-07-23"
    "Arizona, Part 2" = "good"
    "Come Tomorrow" = "bad"
    "Far Away From You" = ""
    "Nothing" = "bad"
    "Spirit" = ""
    "Stoned in Love" = "bad"
    "Time of Your Life" = "short"
    "Turning Corners" = ""
    "U R Always" = "bad"
    "Way I’m Feelin’" = ""

["Childish Gambino"]

  ["Childish Gambino"."Because the Internet"]
    "@date" = "2013-12-06"
    "@yt" = "ExVtrghW5Y4"
    "Death by Numbers" = "short"
    "Dial Up" = "short"
    "Earth: The Oldest Computer (The Last Night)" = ""
    "I. Crawl" = ""
    "I. Flight of the Navigator" = ""
    "I. The Party" = "short"
    "I. The Worst Guys" = ""
    "II. No Exit" = "short"
    "II. Shadows" = ""
    "II. Worldstar" = ""
    "II. Zealots of Stockholm (Free Information)" = ""
    "III. Telegraph Ave. (\"Oakland\" by Lloyd)" = ""
    "III. Urn" = "short"
    "IV. Sweatpants" = ""
    "Life: The Biggest Troll (Andrew Auernheimer)" = ""
    "Pink Toes" = ""
    "Playing Around Before the Party Starts" = "short"
    "The Library (intro)" = "short"
    "V. 3005" = ""

  ["Childish Gambino"."Camp"]
    "@date" = "2011"
    "All the Shine" = ""
    "Backpackers" = ""
    "Bonfire" = "bad"
    "Fire Fly" = "bad"
    "Heartbeat" = ""
    "Hold You Down" = ""
    "Kids (Keep Up)" = ""
    "L.E.S." = ""
    "Letter Home" = "short"
    "Outside" = "bad"
    "Sunrise" = ""
    "That Power" = ""
    "You See Me" = ""

  ["Childish Gambino"."“Awaken, My Love!”"]
    "@date" = "2016-12-02"
    "@yt" = "Kp7eSUU9oy8"
    "Baby Boy" = ""
    "Boogieman" = ""
    "California" = "short"
    "Have Some Love" = ""
    "Me and Your Mama" = ""
    "Redbone" = ""
    "Riot" = "short"
    "Stand Tall" = ""
    "Terrified" = ""
    "The Night Me and Your Mama Met" = ""
    "Zombies" = ""

["Chris Isaak"]

  ["Chris Isaak"."Chris Isaak"]
    "@date" = "1986"
    "Blue Hotel" = ""
    "Cryin’" = "short"
    "Fade Away" = ""
    "Heart Full of Soul" = ""
    "Lie to Me" = ""
    "Lovers Game" = "short"
    "This Love Will Last" = "short"
    "Waiting for the Rain to Fall" = ""
    "Wild Love" = "short"
    "You Owe Me Some Kind of Love" = "good"
    "You Took My Heart" = "short"

  ["Chris Isaak"."Heart Shaped World"]
    "@date" = "1989"
    "@yt" = "ib6VAJbEBjg"
    "Blue Spanish Sky" = ""
    "Don't Make Me Dream About You" = ""
    "Forever Young" = ""
    "Heart Shaped World" = ""
    "I'm Not Waiting" = ""
    "In the Heat of the Jungle" = ""
    "Kings of the Highway" = ""
    "Nothing's Changed" = ""
    "Wicked Game" = ""
    "Wrong to Love You" = ""

["Ciara"]

  ["Ciara"."Basic Instinct"]
    "@date" = "2010-12-13"
    "@yt" = "Lp6W4aK1sbs"
    "Basic Instinct (U Got Me)" = ""
    "Gimmie Dat" = ""
    "Girls Get Your Money" = ""
    "Heavy Rotation" = ""
    "I Run It" = ""
    "Ride" = ""
    "Speechless" = ""
    "Turn It Up" = ""
    "Wants for Dinner" = ""
    "Yeah I Know" = ""
    "You Can Get It" = ""

["Cocteau Twins"]
  "@check" = "2020-06-21"

  ["Cocteau Twins"."Blue Bell Knoll"]
    "@date" = "1988-09-19"
    "A Kissed Out Red Floatboat" = ""
    "Athol-Brose" = "bad"
    "Blue Bell Knoll" = ""
    "Carolyn's Fingers" = ""
    "Cico Buff" = "bad"
    "Ella Megalast Burls Forever" = "bad"
    "For Phoebe Still a Baby" = "bad"
    "Spooning Good Singing Gum" = ""
    "Suckling the Mender" = ""
    "The Itchy Glowbo Blow" = "good"

  ["Cocteau Twins"."Four-Calendar Café"]
    "@date" = "1993-11-02"
    "Bluebeard" = "bad"
    "Essence" = ""
    "Evangeline" = "bad"
    "Know Who You Are at Every Age" = ""
    "My Truth" = ""
    "Oil of Angels" = "bad"
    "Pur" = ""
    "Squeeze-Wax" = ""
    "Summerhead" = "good"
    "Theft, and Wandering Around Lost" = ""

  ["Cocteau Twins"."Garlands"]
    "@date" = "1982-09-01"
    "Blind Dumb Deaf" = "bad"
    "Blood Bitch" = "bad"
    "But I’m Not" = "short"
    "Garlands" = "bad"
    "Grail Overfloweth" = "bad"
    "Shallow Then Halo" = "bad"
    "The Hollow Men" = "bad"
    "Wax and Wane" = "bad"

  ["Cocteau Twins"."Head Over Heels"]
    "@date" = "1983-10-31"
    "Five Ten Fiftyfold" = "good"
    "Glass Candle Grenades" = "short"
    "In Our Angelhood" = "good"
    "In the Gold Dust Rush" = "bad"
    "Multifoiled" = "short"
    "Musette and Drums" = "good"
    "My Love Paramour" = "bad"
    "Sugar Hiccup" = "bad"
    "The Tinderbox (of a Heart)" = "good"
    "When Mama Was Moth" = "bad"

  ["Cocteau Twins"."Heaven or Las Vegas"]
    "@date" = "1990-08-21"
    "Cherry-Coloured Funk" = "bad"
    "Fifty-Fifty Clown" = "bad"
    "Fotzepolitic" = ""
    "Frou-Frou Foxes in Midsummer Fires" = ""
    "Heaven or Las Vegas" = "bad"
    "I Wear Your Ring" = ""
    "Iceblink Luck" = "bad"
    "Pitch the Baby" = "bad"
    "Road, River and Rail" = ""
    "Wolf in the Breast" = ""

  ["Cocteau Twins"."Love’s Easy Tears"]
    "@date" = "1986-09-01"
    "Love’s Easy Tears" = "good"
    "Orange Appled" = "short"
    "Sigh’s Smell of Farewell" = ""
    "Those Eyes, That Mouth" = ""

  ["Cocteau Twins"."Lullabies to Violaine, Volume 1"]
    "@date" = "2006-03-21"
    "Aikea-Guinea (alternate version)" = ""
    "Alas Dies Laughing" = ""
    "Because of Whirl-Jack" = ""
    "Eggs and Their Shells" = ""
    "Feathers-Oar-Blades" = ""
    "Great Spangled Fritillary" = ""
    "Hazel" = "short"
    "It’s All but an Ark Lark" = ""
    "Kookaburra" = ""
    "Laughlines" = ""
    "Melonella" = ""
    "Mizake the Mizan" = ""
    "Pale Clouded White" = ""
    "Pearly-Dewdrops’ Drops (alternate version)" = ""
    "Peppermint Pig (7″ version)" = ""
    "Quisquose" = ""
    "Rococo" = ""
    "Sugar Hiccup (12″ version)" = ""
    "Watchlar" = ""

  ["Cocteau Twins"."Milk & Kisses"]
    "@date" = "1996-05-14"
    "Calfskin Smack" = ""
    "Eperdu" = ""
    "Half-Gifts" = ""
    "Rilkean Heart" = ""
    "Seekers Who Are Lovers" = ""
    "Serpentskirt" = "good"
    "Tishbite" = ""
    "Treasure Hiding" = ""
    "Ups" = ""
    "Violaine" = "bad"

  ["Cocteau Twins"."The Pink Opaque"]
    "@date" = "1985-09"
    "Aikea-Guinea" = ""
    "From the Flagstones" = ""
    "Hitherto" = "good"
    "Millimillenary" = "good"
    "Pearly-Dewdrops’ Drops" = ""
    "Pepper-Tree" = ""
    "The Spangle Maker" = ""
    "Wax and Wane (Remix)" = ""

  ["Cocteau Twins"."Tiny Dynamine"]
    "@date" = "1985-11-01"
    "Pink Orange Red" = "good"
    "Plain Tiger" = ""
    "Ribbed and Veined" = "good"
    "Sultitan Itan" = ""

  ["Cocteau Twins"."Treasure"]
    "@date" = "1984-10-01"
    "Aloysius" = "bad"
    "Amelia" = "bad"
    "Beatrix" = "bad"
    "Cicely" = "bad"
    "Donimo" = "bad"
    "Ivo" = "good"
    "Lorelei" = "bad"
    "Otterley" = "good"
    "Pandora (For Cindy)" = "good"
    "Persephone" = "good"

  ["Cocteau Twins"."Victorialand"]
    "@date" = "1986-07-23"
    "Feet-Like Fins" = ""
    "Fluffy Tufts" = ""
    "How to Bring a Blush to the Snow" = ""
    "Lazy Calm" = "good"
    "Little Spacey" = ""
    "Oomingmak" = "short"
    "The Thinner the Air" = ""
    "Throughout the Dark Months of April and May" = "good"
    "Whales Tails" = "good"

["Coldplay"]

  ["Coldplay"."A Rush of Blood to the Head"]
    "@date" = "2002-08-26"
    "@yt" = "RB-RcX5DS5A"
    "A Rush of Blood to the Head" = ""
    "A Whisper" = ""
    "Amsterdam" = ""
    "Clocks" = ""
    "Daylight" = ""
    "God Put a Smile Upon Your Face" = ""
    "Green Eyes" = ""
    "In My Place" = ""
    "Politik" = ""
    "The Scientist" = ""
    "Warning Sign" = ""

["Com Truise"]

  ["Com Truise"."Galactic Melt"]
    "@date" = "2011"
    "Air Cal" = "bad"
    "Brokendate" = ""
    "Cathode Girls" = "bad"
    "Ether Drift" = ""
    "Flightwave" = "bad"
    "Futureworld" = ""
    "Glawio" = ""
    "Hyperlips" = "good"
    "Karova" = ""
    "Terminal" = "short"
    "VHS Sex" = "bad"

  ["Com Truise"."In Decay"]
    "84’ Dreamin" = ""
    "@date" = "2012"
    "Alfa Beach" = "good"
    "Closed" = ""
    "Colorvision" = "good"
    "Controlpop" = ""
    "Data Kiss" = ""
    "Dreambender" = ""
    "Klymaxx" = ""
    "Open" = ""
    "Smily Cyclops" = ""
    "Stop" = ""
    "Video Arkade" = ""
    "Yxes" = ""

  ["Com Truise"."Iteration"]
    "@date" = "2017"
    "Dryswch" = ""
    "Ephemeron" = "bad"
    "Isostasy" = ""
    "Iteration" = ""
    "Memory" = ""
    "Of Your Fake Dimension" = "bad"
    "Propagation" = ""
    "Syrthio" = ""
    "Ternary" = ""
    "Usurper" = ""
    "Vacuume" = ""
    "When Will You Find the Limit" = ""

["Conjure One"]

  ["Conjure One"."Conjure One"]
    "@date" = "2002-09-17"
    "Center of the Sun" = ""
    "Damascus" = "short"
    "Make a Wish" = ""
    "Manic Star" = ""
    "Pandora" = "good"
    "Premonition (reprise)" = ""
    "Redemption" = ""
    "Sleep" = ""
    "Tears From the Moon" = ""
    "Tidal Pool" = "good"
    "Years" = ""

  ["Conjure One"."Exilarch"]
    "@date" = "2010-10-19"
    "Demon Inside" = ""
    "Existential Exile" = ""
    "I Dream in Colour" = ""
    "Like Ice" = "bad"
    "Nargis" = ""
    "Nomadic Code" = ""
    "Oligarch" = ""
    "Places That Don't Exist" = ""
    "Run for Cover" = ""
    "The Distance" = ""
    "Zephyr" = ""

  ["Conjure One"."Extraordinary Ways"]
    "@date" = "2005-08-30"
    "Beyond Being" = ""
    "Dying Light" = ""
    "Endless Dream" = "bad"
    "Extraordinary Way" = ""
    "Face the Music" = "bad"
    "Forever Lost" = ""
    "I Believe" = "bad"
    "Into the Escape" = ""
    "One Word" = "bad"
    "Pilgrimage" = "bad"

["Counting Crows"]

  ["Counting Crows"."August and Everything After"]
    "@date" = "1993-09-14"
    "@yt" = "-oqAU5VxFWs"
    "A Murder of One" = ""
    "Anna Begins" = ""
    "Ghost Train" = ""
    "Mr. Jones" = ""
    "Omaha" = ""
    "Perfect Blue Buildings" = ""
    "Rain King" = ""
    "Raining in Baltimore" = ""
    "Round Here" = ""
    "Sullivan Street" = ""
    "Time and Time Again" = ""

  ["Counting Crows"."This Desert Life"]
    "@date" = "1999-11-01"
    "All My Friends" = ""
    "Amy Hit the Atmosphere" = ""
    "Colorblind" = "good"
    "Four Days" = ""
    "Hanginaround" = ""
    "High Life" = ""
    "I Wish I Was a Girl" = ""
    "Mrs. Potter’s Lullaby" = ""
    "Speedway" = ""
    "St. Robinson in His Cadillac Dream / Kid Things" = ""

["Crazy P"]

  ["Crazy P"."Age of the Ego"]
    "@date" = "2019-05-03"
    "Barefooted" = ""
    "Is This All It Seems" = ""
    "Kari" = ""
    "Lean on Me" = ""
    "Love Is With You" = ""
    "Night Rain" = "good"
    "SOS" = ""
    "Step Into the Light" = ""
    "The Witness" = ""
    "This Fire" = ""
    "We Will Fuck You Up" = ""

  ["Crazy P"."Stop Space Return"]
    "@date" = "2008-10-13"
    "Caught Up" = ""
    "Fascination" = ""
    "Give a Little" = "bad"
    "In and Out" = "good"
    "Lie Lost" = ""
    "Love on the Line" = "bad"
    "Never Gonna Reach Me" = ""
    "Over to You / Say Goodbye" = ""
    "Stop Space Return" = ""
    "Too Far" = ""
    "Wishing For" = ""

  ["Crazy P"."Walk Dance Talk Sing"]
    "@date" = "2015"
    "Cruel Mistress" = ""
    "Echo" = ""
    "Hear My Song" = ""
    "Like a Fool" = "good"
    "Magnetise" = ""
    "Scrap the Book" = ""
    "Something More" = ""
    "The Come On" = ""
    "The Way" = ""
    "Walk Dance Talk Sing" = ""
    "Witch Doctor" = ""

  ["Crazy P"."When We On"]
    "@date" = "2011"
    "Beatbox" = ""
    "Changes" = ""
    "Eruption" = ""
    "Future Beat" = ""
    "Heartbreaker" = "good"
    "Open for Service" = ""
    "Sonar" = ""
    "The Unbearable Lightness of Being" = ""
    "Twisted" = ""
    "Wecanonlybewhoweare" = ""
    "Your Dark Energy" = ""

["Curve"]

  ["Curve"."Cuckoo"]
    "@date" = "1993"
    "All of One" = ""
    "Crystal" = ""
    "Cuckoo" = ""
    "Left of Mother" = ""
    "Men Are From Mars, Women Are From Venus" = "good"
    "Missing Link" = ""
    "Superblaster" = ""
    "Sweetest Pie" = ""
    "Turkey Crossing" = ""
    "Unreadable Communication" = ""
