["Cocteau Twins"]
check = 2020-06-21

["Cocteau Twins".album."Treasure"]
date = 1984-10-01
song = [
   { "Ivo" = "good" },
   { "Lorelei" = "bad" },
   { "Beatrix" = "bad" },
   { "Persephone" = "good" },
   { "Pandora (For Cindy)" = "good" },
   { "Amelia" = "bad" },
   { "Aloysius" = "bad" },
   { "Cicely" = "bad" },
   { "Otterley" = "good" },
   { "Donimo" = "bad" }
]
